services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u${DB_USER} -p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --ssl-keyfile key.pem --ssl-certfile cert.pem
    volumes:
      - .:/app
    ports:
      - "8002:8002"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:

volumes:
  mysql_data:
