version: '3.8'

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev -- --host
  